name = "discordapi-ad-server"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[triggers]
crons = ["0 * * * *"]

[env.staging]
name = "discordapi-ad-server-staging"

[env.staging.triggers]
crons = ["0 * * * *"]

[env.production]
name = "discordapi-ad-server"

[env.production.triggers]
crons = ["0 * * * *"]
